checkpoints_folder: /ephemeral/outputs/09-07-classic-par-2
checkpoint_file: epoch_1000.pt
config_file: config.yaml
device: "cuda"
dataloader:
  split: test
  batch_size: 128
  num_workers: 4
shapenet:
  path: "data/ShapeNet"
  normalize: false
  categories: null
evaluation:
  resolution: 50 