checkpoints_folder: /ephemeral/outputs/18-07-multigpu-normalized-low-sps-2nd-aprt
checkpoint_file: epoch_2000.pt
config_file: config.yaml
device: "cuda"
dataloader:
  split: test
  batch_size: 128
  num_workers: 4
shapenet:
  path: "data/ShapeNet"
  normalize: true
  categories: null
evaluation:
  resolution: 100 