checkpoints_folder: /ephemeral/outputs/28-07-normalized-second
checkpoint_file: epoch_1000.pt
config_file: config.yaml
device: "cuda"
dataloader:
  dataset: scenes_dataset 
  batch_size: 128
  num_workers: 4
shapenet:
  split: test
  path: "data/ShapeNet"
  normalize: true
  categories: null
scenes_dataset:
  split: val
  path: "data/scannetpp"
  normalize: true
  gt: true
  fps: true
evaluation:
  resolution: 100 