checkpoints_folder: /ephemeral/outputs/18-07-multigpu-normalized-low-sps-2nd-aprt
epoch: 2000
config_file: config.yaml
device: "cuda"
dataset: scene
dataloader:
  split: val
  batch_size: 128
  num_workers: 4
shapenet:
  path: "data/ShapeNet"
  normalize: false
  categories: null
scene:
  path: "data/replica"
  name: 'office1'
  z_up: true
evaluation:
  resolution: 5 