checkpoints_folder: /ephemeral/outputs/28-07-normalized-second
epoch: 1000
config_file: config.yaml
device: "cuda"
dataset: scene
dataloader:
  split: val
  batch_size: 128
  num_workers: 4
shapenet:
  path: "data/ShapeNet"
  normalize: true
  categories: null
scene:
  path: "/ephemeral/scannetpp"
  name: '2a1b555966'
  z_up: true
  gt: true
evaluation:
  resolution: 5 