checkpoints_folder: checkpoints/shapenet
config_file: config.yaml
device: "cuda"
dataset: shapenet
dataloader:
  split: test
  batch_size: 128
  num_workers: 4
shapenet:
  path: "data/ShapeNet"
  normalize: false
  categories: null
scene:
  path: PATH_TO_YOUR_SCENE_DATASET
  name: SCENE_ID
  z_up: true
  gt: true
evaluation:
  resolution: 50 