checkpoints_folder: /ephemeral/outputs/09-07-classic-par-1
epoch: 175
config_file: config.yaml
device: "cuda"
dataloader:
  split: val
  batch_size: 128
  num_workers: 4
shapenet:
  path: "data/ShapeNet"
  normalize: false
  categories: null
evaluation:
  resolution: 10 
output_path: /ephemeral/outputs/09-07-classic-par-1