checkpoints_folder: /ephemeral/outputs/09-07-classic-par-3-heads-1000-points-cubes
epoch: 5
config_file: config.yaml
device: "cuda"
dataloader:
  split: val
  batch_size: 128
  num_workers: 4
shapenet:
  path: "data/ShapeNet"
  normalize: false
  categories: null
evaluation:
  resolution: 5 